### ISSUE TITLE
Please document how to use nostr-tools in the browser

### ISSUE THREAD

**Issue by Giszmo** [fiatjaf/nostr-tools#14]
How do I create an index.html that when loaded allows me to do all the stuff from the Readme.md in the dev console?

**Comment by fiatjaf** [comment]
https://github.com/fiatjaf/nostr-tools#using-from-the-browser-if-you-dont-want-to-use-a-bundler

**Comment by Giszmo** [comment]
Sadly that instruction is broken now.
