### ISSUE TITLE
Interest in TypeScript definitions?

### ISSUE THREAD

**Issue by rcoder** [fiatjaf/nostr-tools#17]
I'm starting to work on a new Nostr client and generally prefer to do my JS-ecosystem work in TypeScript from the start. Would y'all be interested in a contributed set of TS declarations for this library?

I know things are moving fast in Nostr-land and I don't want to create a ton of extra hassle around API changes, but it would also be cool to not "miss the boat" on TS support (i.e., wait until the API footprint + quantity of existing loosely-typed code is just too huge to retrofit TS everywhere) as SSB, Dat, and others have sadly done over the years.

To be clear: I don't mean to imply that this project is doomed or not "serious" simply because you're using vanilla JS. I'm just an old, forgetful dev who likes to have my compiler + editor remind me what's ok/not-ok when I come back to code I haven't looked at in a while. :)

**Comment by fiatjaf** [comment]
Yes, that would be great!

But you must tell me how do I check if I broke something if I ever change the APIs, just so I don't break things or update the TS declarations accordingly.

**Comment by fiatjaf** [comment]
If you want to change the API a little so it fits TypeScript better please do it. There are some weird choices I made here.
