### ISSUE TITLE
cross-fetch is not available in service workers

### ISSUE THREAD

**Issue by Giszmo** [fiatjaf/nostr-tools#22]
I'm trying to use nip05.js and run into [this issue](https://github.com/lquixada/cross-fetch/issues/78).

```
import crossFetch from 'cross-fetch'

const f = (typeof XMLHttpRequest == 'function')
  ? crossFetch
  : fetch
```

using `f` instead of `fetch` makes it fetch stuff in my service worker but I haven't tested this enough to make a PR yet.

**Comment by fiatjaf** [comment]
Should be fixed now. `node-fetch` is not used anymore, if using nip05 in nodejs you'll have to supply it yourself.
