### ISSUE TITLE
Implement nip 20

### ISSUE THREAD

**Issue by arejula27** [fiatjaf/nostr-tools#32]
Add support for https://github.com/nostr-protocol/nips/blob/master/20.md, so we can get an OK (or not ok) response for each event published.

**Comment by arejula27** [comment]
As I commented in the pr #30 would be a good idea to have two implementations, one synchronous and other asynchronous

**Comment by arejula27** [comment]
We should discuss if we want to implement this nip with a call back function or more like a *wait until* when publishing and event. Opinions?

**Comment by fiatjaf** [comment]
If you just return a Promise the caller can choose to use `await` or not. Let's not use callbacks if possible.

**Comment by arejula27** [comment]
As i see the response will come from the web socket of line 75 in *relay.js", so i dont think is posible to handle it on the pusblish function of pool.js. Maybe i dont understand correctly?

**Comment by arejula27** [comment]
i tthink i get it, pr later :D

**Comment by fiatjaf** [comment]
You can create a Promise and return it, but keep a reference to the `resolve` function of that promise, then call it when you want.

(for future reference)

**Comment by fiatjaf** [comment]
This is done with event listeners.
