### ISSUE TITLE
Filter Logical Operation AND

### ISSUE THREAD

**Issue by arejula27** [fiatjaf/nostr-tools#40]
Looks like the filter works as OR operation:
events with kind 4 OR authors in [...]
Is there a way for treat them as AND?

**Comment by arejula27** [comment]
After checking it is on the other way, each filter is and AND so would be interesting to have an OR operand

**Comment by fiatjaf** [comment]
Each filter is an `AND`, but you can use multiple filters together, in that case they mean `OR`.

```
[
  [{"ids": [1, 2], "authors": ["abcdef"]}],
  [{"#p": ["abcdef"]}]
]
```

is equivalent to

`(id = 1 OR id = 2 AND author = 'abcdef') OR p = 'abcdef'`

**Comment by arejula27** [comment]
I thought it wasn't implemented so I would do it, nice.
