### ISSUE TITLE
Getting a "GET https://unpkg.com/nostr-tools@0.24.1/standalone/index.js net::ERR_ABORTED 404" when 

### ISSUE THREAD

**Issue by joajimenez** [fiatjaf/nostr-tools#43]
When I try to use Nostr tools from the browser, I'm getting an "GET https://unpkg.com/nostr-tools@0.24.1/standalone/index.js net::ERR_ABORTED 40 error."

![Screenshot from 2022-12-20 11-43-47](https://user-images.githubusercontent.com/428554/208707148-5b55abdb-a2c3-4eca-b798-1d3b8c049ef5.png)

**Comment by fiatjaf** [comment]
Please wait for the next release.

**Comment by fiatjaf** [comment]
The new release has arrived. The path has changed to https://unpkg.com/nostr-tools/lib/nostr.bundle.js.
