### ISSUE TITLE
fix import statements in readme 

### ISSUE THREAD

**Issue by wds4** [fiatjaf/nostr-tools#44]
Looks like the recently updated examples in readme need import statements to be fixed,  e.g. change:
```
const {matchFilters} = require('./cjs')
```
to
```
import {matchFilters} from 'nostr-tools'
```
I'll see if I can get a pull request going for that.

**Comment by fiatjaf** [comment]
Thank you, but there is no need to open issues before PRs. I know this is somehow a "best practice" around GitHub, but it annoys me very much. I should add to the README, but I would have to add it to all READMEs of all my repositories and that would be hard.
