### ISSUE TITLE
Proper doc

### ISSUE THREAD

**Issue by arejula27** [fiatjaf/nostr-tools#49]
The project is growing and more people would like to use kt. It is a interesting idea to have  a proper doc deployed via gh actions, what about Astro? I can try to do it for Christmas. People would find more usable the API if there is a good documentation instead just a read.me

**Comment by fiatjaf** [comment]
I think it is better to not have that, or I will have to maintain it going forward.

**Comment by arejula27** [comment]
If the project grows, how will people know to use that without documentation. Maybe a web is too much but I think the repo should have a list of public functions, it's parameters and what it does. In my case the readme was not enough and had to read the code.

**Comment by arejula27** [comment]
Maybe a documentation as gin gonic will be a middle term. https://github.com/gin-gonic/gin/blob/master/README.md

**Comment by fiatjaf** [comment]
I think people should be able to read the code. That is much healthier than poorly-maintained documentation pages.

If the project grows, as you say, then we can add documentation, but later, let's wait at least 6 months.
