### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by pseudozach** [fiatjaf/nostr-tools#51]
I just need to publish some notes to a few relays, not much else. 
Trying to use this on serverless api endpoint with next.js on vercel and it gives this error

>import { relayInit } from 'nostr-tools';

>ReferenceError: fetch is not defined

I did `npm i node-fetch@2` but still same error.

**Comment by fiatjaf** [comment]
You must call `nip05.useFetchImplementation(require('node-fetch'))`.
