### ISSUE TITLE
Usage of `fetch` unclear

### ISSUE THREAD

**Issue by PythooonUser** [fiatjaf/nostr-tools#53]
I get the following error whenever I simply require/import `nostr-tools`:

```
[...]\node_modules\nostr-tools\lib\nostr.cjs.js:438
var _fetch = fetch;
             ^

ReferenceError: fetch is not defined
```

I'm using Windows and I installed `node-fetch`. I'm pretty sure I'm missing something obvious.

**Comment by PythooonUser** [comment]
I made it work by reading the ` node-fetch` documentation, I needed to provide the following in the beginning:

```js
const fetch = require("node-fetch");
if (!globalThis.fetch) {
  globalThis.fetch = fetch;
}
```

**Comment by fiatjaf** [comment]
The README says this:

```
// on nodejs, install node-fetch@2 and call this first:
nip05.useFetchImplementation(require('node-fetch'))
```

I don't know how to make it clearer there. Help wanted.
But your solution is even better.

**Comment by PythooonUser** [comment]
Yeah, from that comment I thought it was only NIP05 specific, but it actually isn't.
And for me the above didn't do the trick.

**Comment by fiatjaf** [comment]
Why isn't it for NIP05 only?

**Comment by wires** [comment]
I think I'm running into the same (expected) issue (using typescript + node). If I create just a file `index.mts`

```js
import fetch from 'node-fetch'
import * as NT from 'nostr-tools'
NT.nip05.useFetchImplementation(fetch)
```
and the compile (`tsc`) and run `node index.mjs`

```
node_modules/.pnpm/nostr-tools@1.0.0-rc1/node_modules/nostr-tools/lib/nostr.cjs.js:412
var _fetch = fetch;
             ^
ReferenceError: fetch is not defined
```

I do the import like this, because for a named import node complains 

```
import { nip05 } from 'nostr-tools';
         ^^^^^
SyntaxError: Named export 'nip05' not found. The requested module 'nostr-tools' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'nostr-tools';
const { nip05 } = pkg;
```
This is with the following `tsconfig.json` file:

```json
{ "compilerOptions": {
    "target": "ES2015",
     // cannot find modules otherwise
     "moduleResolution": "node"
} }
```

Before the function is defined in `nostr.cjs.js` at line 412 (see above) fetch is referenced anyway to assign to `_fetch`. This probably shouldn't happen this way, maybe wrapped in a `try .. catch` block?

```
var _fetch;
try {
  _fetch = fetch;
} catch {}
function useFetchImplementation(fetchImplementation) {
  _fetch = fetchImplementation;
}
```

**Comment by fiatjaf** [comment]
Do you know what I have to do to make the ESM imports work?

**Comment by fiatjaf** [comment]
By the way if you're importing from TypeScript you can import stuff directly I think. Like `import { getPublicKey } from 'nostr-tools/keys'`. I haven't tried that and I don't understand JavaScript modules, but I think it will work.
