### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

### ISSUE THREAD

**Issue by joajimenez** [fiatjaf/nostr-tools#54]
Getting this error while using the bundle.

![Screenshot from 2022-12-21 17-17-28](https://user-images.githubusercontent.com/428554/209004664-c1862d25-ea7f-45bd-83f7-7bf95851956b.png)

**Comment by fiatjaf** [comment]
This should be fixed i the latest version if you `await` to the `connect()` function before trying to send stuff.
