### ISSUE TITLE
ReferenceError: WebSocket is not defined

### ISSUE THREAD

**Issue by zeSchlausKwab** [fiatjaf/nostr-tools#57]
I'm getting `ReferenceError: WebSocket is not defined` when calling `const relay = relayInit('wss://nostr-pub.wellorder.net')` on `1.0.0-rc1`

**Comment by fiatjaf** [comment]
On Node.js?

**Comment by fiatjaf** [comment]
See https://github.com/fiatjaf/nostr-tools#interacting-with-a-relay. On Node.js you must install and import `websocket-polyfill` first.

**Comment by eko2one** [comment]
I am using Nuxt 3 and getting:
`[nuxt] [request error] [unhandled] [500] WebSocket is not defined`

Although I have installed and then imported `websocket-polyfill ` in my `~/server/api/test.ts` 
Seems like I have to specifically declare `WebSocket` but could not figure out how.
