### ISSUE TITLE
Unsecure signature scheme

### ISSUE THREAD

**Issue by fix** [fiatjaf/nostr-tools#59]
Hi pointing out 2 security issues here around the signature
1. implementation:
https://github.com/fiatjaf/nostr-tools/blob/master/event.ts#L67
If you give to the function a fake id (of another event), it opens to an attack where a user can sign another message. I would compute again the hash of the event only instead. Event for the whole protocole, i would completely get rid-off the id in the transmission to force recomputing the hash on reception.
2. protocole wise:
It is not a good practice to blindly sign a hash, it could be used for some pre-image attacks scheme. It is usually a good practice to prefix with the "meaning" of the signature. That way it can't be reused for another purpose.

For instance here it could be hash("nostr-nip01" | hash(event)). This way even in blind signature (it can happens in some uses cases like hardware when you can't verify the meaning of the event) can be secured

**Comment by fiatjaf** [comment]
Thank you.

1. Good point, I will do that. Yes, we should get rid of the id and force recomputing, that was an error in the protocol design.
2. You are definitely right on this and I wish you had told me this 2 years ago, but unfortunately we'll have to live with it now because it is not worth changing at this point.

**Comment by fix** [comment]
Hi thanks for the answer. Not reopening the issue but adding a couple of thoughts:
- i believe there will be more security issues uncovered with more people using it
- protocol will likely iterate

Your answer is to me not reassuring, but it is likely because it is difficult to up grade the protocol because there is not upgrade mechanism. I understand you want to keep the thing clean and lean, but i think however an upgrade mechanism in the protocol (as simple as adding a version and optionally capabilities switches) would improve the situation.

This comment does not need an answer

**Comment by fix** [comment]
sorry to insist here, this
https://github.com/fiatjaf/nostr-tools/blob/master/event.ts#L79

is still unsecured because you can pass virtually any id thus you may make all events verified. You need to recompute the id every time if there is a secure assumption for it

**Comment by fix** [comment]
pull request here https://github.com/fiatjaf/nostr-tools/pull/71

**Comment by adamritter** [comment]
You're right, but it's generally easier to submit a patch and leave just
the merge part to the reviewer, as he is the bottleneck in the development
of nostr.

fiatjaf merged all my pull requests very fast, I think he's doing a great
job, but it's important to not give him coding jobs, as maintenance is hard
enough.

**Comment by adamritter** [comment]
thanks, I didn't see it for some reason

**Comment by fix** [comment]
yo, no pb, i did it in async way lol
