### ISSUE TITLE
Vanilla repo clone, failing test in `nip04.test.js`

### ISSUE THREAD

**Issue by StevenBlack** [fiatjaf/nostr-tools#62]
Hello 👋🏻 checking out these tools, looks great!  

### Problem

After a vanilla repo clone and `yarn`, 17/18 tests pass, one test fails.

### Steps to reproduce

1. `git clone` the repo into clean userspace.
2. Run `yarn` to bring everything in.
3. run `npm test` and observe (see screen capture below)

<img width="579" alt="2022-12-23_21-02-55" src="https://user-images.githubusercontent.com/80144/209417866-1a6c0eb3-e103-42bd-81b1-36d4e4a5877e.png">

**Comment by StevenBlack** [comment]
Is this is because `Crypto.subtle` isn't available in insecure contexts? I'm unsure if this test is supposed to work in a terminal sesh or... 🤔?

**Comment by fiatjaf** [comment]
It should be supported in Node.js for the tests to run. What is your Node.js version?

**Comment by StevenBlack** [comment]
@fiatjaf 17/18 tests pass on Node `v16.14.0` and `v16.12.0` — two different boxes.

Upgrading node with...

```
nvm install stable --reinstall-packages-from=current
```

... brings me to `v19.3.0` and all tests pass now.

Trying it with Node `v18.12.1` which is `lts/hydrogen` I see 17/18 tests passing.

So Node `v19` appears to be a requirement.

**Comment by StevenBlack** [comment]
@fiatjaf PR #62 adds this to the readme.

**Comment by lylepratt** [comment]
I had to force a global for `crypto` to point to `webcrypto` in my module to get this to work:
`global.crypto = require('crypto').webcrypto;`

**Comment by StevenBlack** [comment]
Lyle @lylepratt I believe the actual issue here is @fiatjaf appears enamoured with claiming light dependency — or "*Only depends on...*" as it inaccurately says now — as opposed to properly documenting this.  

Or to restate this cleanly: adding Node v19 as was suggested in closed PR #62 is evidently a bridge too far for some unstated reason.

A fluff claim, however inaccurate, matters more than bum-steering users. That's my take, and why I'm presently using, and contributing to, something else.
