### ISSUE TITLE
TypeError: resolveClose is not a function

### ISSUE THREAD

**Issue by FreeTrade** [fiatjaf/nostr-tools#70]
Uncaught (in promise) TypeError: resolveClose is not a function
    Ember 10
        onclose
        NostrTools
        connectRelay
        connect

Seeing this error quite a lot. Looks like scope error.

**Comment by fiatjaf** [comment]
I believe this is solved on the latest version (1.0.1). Can you confirm?

**Comment by FreeTrade** [comment]
Confirmed, thank you.
