### ISSUE TITLE
Use noble-hashes instead of create-hash

### ISSUE THREAD

**Issue by paulmillr** [fiatjaf/nostr-tools#9]
Since you are using noble-hashes through micro-bip already, it makes sense to use its sha256.

Also `import { randomBytes } from '@noble/hashes/utils';`

**Comment by fiatjaf** [comment]
I'm also already using `create-hash` because of `browserify-cipher`, which is needed for the AES-CBC thing I have here.

That brings me to the question: when are we going to get `@noble/aes`?

**Comment by fiatjaf** [comment]
This will work, right? https://github.com/fiatjaf/nostr-tools/commit/2230f32d1123a30ac7c4f81acad07ef576bcaa96

**Comment by fiatjaf** [comment]
Also: https://github.com/paulmillr/micro-bip39/issues/2

**Comment by paulmillr** [comment]
yes, remove create-hash from deps

**Comment by fiatjaf** [comment]
Done.
